- deployment/docker-compose.yml
The docker-compose doesn't find the tag.
> Fix-docker-compose

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/fr.yml
- README.md
This PR adds a `contribute` section, useful to have an overview of the contribution process
> Add contribue section in the main `README`

- LICENSE.txt
- README.md
This PR add the project license.
> Add project license

- README.md
- deployment/frontend.env
- frontend/.env
- frontend/src/App.tsx
- frontend/src/index.tsx
This PR introduces the possibility of setting a custom timeout for the backend responses.
> Add customization of timeout for backend's responses

- frontend/src/common.ts
- frontend/src/components/AddPlant.tsx
- frontend/src/components/AllLogs.tsx
- frontend/src/components/Auth.tsx
- frontend/src/components/EditEvent.tsx
- frontend/src/components/Home.tsx
- frontend/src/components/PlantDetails.tsx
- frontend/src/components/SearchPage.tsx
- frontend/src/components/Settings.tsx
- frontend/src/components/UserPlant.tsx
This PR introduces a better error handling
> feature: better error handling

- frontend/src/components/ErrorDialog.tsx
This PR introduces the word wrap for the error dialog.
> Add word wrap in error dialog

- backend/src/main/java/com/github/mdeluise/plantit/plant/PlantController.java
- frontend/src/components/AddPlant.tsx
- frontend/src/components/Home.tsx
This PR introduces the alphabetical sort for the plants in the homepage.
> Sort plants alphabetically in homepage

- README.md
- frontend/src/components/AddPlant.tsx
- frontend/src/components/Auth.tsx
- frontend/src/components/LogEntry.tsx
- frontend/src/components/PlantDetails.tsx
- frontend/src/components/SearchPage.tsx
This PR adds some little improvements:
- add missing event types colors and icons
- add skeleton for image loading in the "add plant" window
- other small shanges
> Some little improvements

- frontend/src/components/EditEvent.tsx
- frontend/src/components/PlantDetails.tsx
This PR introduces live update of the uploaded plant images.
Before this PR in order to view an uploaded image, the `Plant Overview` window needed to be re-rendered.
> Uploaded plant image immediately shown

- frontend/src/components/Home.tsx
- package-lock.json
This PR introduces the alphabetical sorting of the event type
> Sort event types alphabetically

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/fr.yml
- .github/pull_request_template.md
This PR improve the github templates.
> Improve GitHub templates

- frontend/src/common.ts
- frontend/src/components/AddPlant.tsx
- frontend/src/components/PlantDetails.tsx
- frontend/src/components/SearchPage.tsx
This PR fixes some problem on photo uploads.
Sometime the new photos are rendered as "loading" without changing state.
> Fix photo upload problems

- backend/src/main/java/com/github/mdeluise/plantit/authentication/UserController.java
- backend/src/main/java/com/github/mdeluise/plantit/authentication/UserDTO.java
- backend/src/main/java/com/github/mdeluise/plantit/authentication/UserDTOConverter.java
- backend/src/main/java/com/github/mdeluise/plantit/authentication/UserService.java
- backend/src/main/java/com/github/mdeluise/plantit/authentication/payload/request/ChangePasswordRequest.java
- frontend/src/components/Settings.tsx
- frontend/src/style/Settings.scss
This PR introduces improvements in the `settings` window of the application:
- add username change feature
- add password change feature
- group together similar settings
Before and after the PR:
<p align="center">
</p>
> Improve and add functionalities in `settings` window

- frontend/src/components/EditEvent.tsx
- frontend/src/components/Home.tsx
This PR fixes #50, i.e. on event modification, place that items correctly into the list.
> Fix modified event places sorted correctly in the list

- backend/TESTING-GUIDELINE.md
- backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoController.java
- backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoDTO.java
- backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoService.java
- backend/src/main/java/com/github/mdeluise/plantit/diary/Diary.java
- backend/src/main/java/com/github/mdeluise/plantit/diary/DiaryService.java
- backend/src/main/java/com/github/mdeluise/plantit/diary/entry/DiaryEntryController.java
- backend/src/main/java/com/github/mdeluise/plantit/diary/entry/DiaryEntryService.java
- backend/src/main/java/com/github/mdeluise/plantit/image/ImageController.java
- backend/src/main/java/com/github/mdeluise/plantit/image/storage/FileSystemImageStorageService.java
- backend/src/main/java/com/github/mdeluise/plantit/plant/Plant.java
- backend/src/main/java/com/github/mdeluise/plantit/plant/PlantController.java
- backend/src/main/java/com/github/mdeluise/plantit/plant/PlantDTO.java
- backend/src/main/java/com/github/mdeluise/plantit/plant/PlantService.java
- backend/src/test/java/com/github/mdeluise/plantit/botanicalinfo/controller/BotanicalInfoControllerTest.java
- backend/src/test/java/com/github/mdeluise/plantit/botanicalinfo/service/BotanicalInfoServiceTest.java
- backend/src/test/java/com/github/mdeluise/plantit/diary/controller/DiaryEntryControllerTest.java
- backend/src/test/java/com/github/mdeluise/plantit/diary/entry/service/DiaryEntryServiceTest.java
- backend/src/test/java/com/github/mdeluise/plantit/diary/service/DiaryServiceTest.java
- backend/src/test/java/com/github/mdeluise/plantit/image/controller/ImageControllerTest.java
- backend/src/test/java/com/github/mdeluise/plantit/image/storage/service/FileSystemImageStorageServiceTest.java
- backend/src/test/java/com/github/mdeluise/plantit/plant/controller/PlantControllerTest.java
- backend/src/test/java/com/github/mdeluise/plantit/plant/service/PlantServiceTest.java
- frontend/src/components/AddPlant.tsx
This PR introduce some unit test for the backend.
Some other tests are required for the backend, and will be added in a future pull request.
This PR (partially) fixes issue #12.
> Fix missing unit test

- .gitmodules
- online-resources/documentation/hugo.toml
This PR fixes some small problems in the presentation and documentation webpages.
> Fix presentation site theme and documentation edit buttons

- online-resources/documentation/content/support/local-environment.md
This PR fix the documentation about local environment variables
> Fix documentation about local environment variable

- frontend/src/components/SearchPage.tsx
In this update, I've implemented a throttle mechanism when searching for species.
Prior to the throttle implementation, numerous requests inundated the backend during species searches. This enhancement aims to streamline the search process and optimize the overall user experience.
> Add throttling when searching for a species

- frontend/src/components/Settings.tsx
In this update, I've implemented a check in the settings window in order to notify if a new version of the system is available.
This is useful in order to know if the server docker images can be updated.
> Add check for system version

- backend/src/main/java/com/github/mdeluise/plantit/diary/entry/DiaryEntryService.java
I've resolved an issue related to the event update feature. Previously, users encountered difficulties updating events, but this problem has now been successfully addressed.
This fix ensures that users can seamlessly update events without any problem.
Simply navigate to the events section, select the event you wish to update, and proceed with the necessary modifications. 
> Fix update events not working

- backend/src/main/java/com/github/mdeluise/plantit/stats/StatsController.java
- backend/src/main/java/com/github/mdeluise/plantit/stats/StatsService.java
- backend/src/main/java/com/github/mdeluise/plantit/systeminfo/GitHubReleaseInfo.java
- backend/src/main/java/com/github/mdeluise/plantit/systeminfo/GitHubSystemVersionService.java
- backend/src/main/java/com/github/mdeluise/plantit/systeminfo/SystemInfoController.java
- backend/src/main/java/com/github/mdeluise/plantit/systeminfo/SystemVersionInfo.java
- backend/src/main/java/com/github/mdeluise/plantit/systeminfo/SystemVersionService.java
I've revamped the way the system checks for the latest and current version, with a special focus on scenarios when the development profile (`dev`) is active.
This improvement ensures a more robust version checking mechanism, especially in development environments. It guarantees accurate reporting of the latest and current system versions, contributing to a smoother overall experience.
No action needed from your end! The system will now handle version checks more efficiently, providing accurate information about the latest and current versions.
> Better retrieve of the system version

- frontend/src/components/AddPlant.tsx
- frontend/src/components/ReleasesNotes.tsx
- frontend/src/components/Settings.tsx
Hi Plant-it Community!
* Search Species Section: Now, the "not provided" phrase is displayed even in the search species section, ensuring better clarity.
Latest Check Fix: Addressed and fixed an issue with the latest version check feature.
> Small fixes and improvements

- backend/src/main/java/com/github/mdeluise/plantit/systeminfo/SystemVersionService.java
This PR fixes an issue regards the fetching of the current project version.
> Fix current project version

- backend/src/main/java/com/github/mdeluise/plantit/image/ImageUtility.java
- backend/src/main/java/com/github/mdeluise/plantit/image/storage/FileSystemImageStorageService.java
- backend/src/test/java/com/github/mdeluise/plantit/image/storage/service/FileSystemImageStorageServiceTest.java
- frontend/public/sw.js
- frontend/src/components/AddPlant.tsx
- frontend/src/components/BottomBar.tsx
- frontend/src/components/EditEvent.tsx
- frontend/src/components/HelpTooltip.tsx
- frontend/src/components/Home.tsx
- frontend/src/components/PlantDetails.tsx
- frontend/src/components/ReadMoreReadLess.tsx
<br/>
I've made some improvements and fixes to enhance the user experience. Let me break down the changes.
* Fixed an issue with PNG transparent images where their thumbnails were not displayed, resulting in an error. (fixing #56)
* App error messages are now displayed as snackbars instead of blocking dialogs.
* Improved offline mode caching for a smoother experience.
* Disabled buttons for submitting or editing data when offline.
* Improved the display of species synonyms for better readability.
These changes address specific issues and enhance the overall usability of the application, making it more reliable, user-friendly, and visually appealing.
Feel free to explore the app as usual, and you'll notice these improvements seamlessly integrated into your …
> Fixes and enhancements

- frontend/src/components/AddPlant.tsx
- online-resources/documentation/content/features/reminders.md
- online-resources/documentation/content/installation/configurations.md
<br/>
This PR fixes a problem with the purchased date of a plant.
<br/>
<br/>
> Start date for plants now works fine

- backend/src/main/java/com/github/mdeluise/plantit/notification/dispatcher/NotificationDispatcherController.java
- backend/src/main/java/com/github/mdeluise/plantit/notification/otp/OtpRepository.java
- backend/src/main/java/com/github/mdeluise/plantit/notification/otp/OtpService.java
- backend/src/main/java/com/github/mdeluise/plantit/plantinfo/PlantInfoExtractorFacade.java
- backend/src/main/java/com/github/mdeluise/plantit/reminder/ReminderDispatcher.java
- backend/src/main/resources/application-dev.properties
- backend/src/main/resources/application-integration.properties
- backend/src/test/java/com/github/mdeluise/plantit/unit/service/OtpServiceUnitTests.java
- frontend/src/components/AddOrModifyReminder.tsx
- frontend/src/components/AddPlant.tsx
- frontend/src/components/Auth.tsx
- frontend/src/components/PlantDetails.tsx
<br/>
This PR tackles several minor issues related to:
- Rendering of reminders
- Reminder dispatchers
- Editing of plant's fields
- Signup with OTP code flow
These changes aim to enhance the overall user experience by resolving these small yet impactful issues.
Users can simply update to the latest version to benefit from the improvements made in rendering reminders, managing reminder dispatchers, editing plant's fields, and signing up using the OTP code flow.
<br/>
<br/>
> Addressing various small issues

- frontend/lib/l10n/app_en.arb
- frontend/lib/l10n/app_uk.arb
<br/>
I've added a Ukrainian language!
Pluralization is complicated in Ukrainian, I think my idea should work fine, but requires a bit more testing
<br/>
<br/>
> feat(lang): add Ukrainian language

- frontend/lib/l10n/app_es.arb
<br/>
Translated Plant-it to spanish.
<br/>
<br/>
> Translated to spanish

- frontend/lib/l10n/app_es.arb
- frontend/web/manifest.json
<br/>
When you install the webapp, it shows the default name.
<br/>
<br/>
> Changed the default name and description of webapp

- frontend/lib/set_server.dart
> changed hintText of setServer to match documentation and default settings

- frontend/lib/l10n/app_pt.arb
<br/>
Added the translation for Portuguese
<br/>
<br/>
> add Portuguese language

- README.md
- frontend/lib/l10n/app_da.arb
<br/>
There was a need for a Danish translation, so I (a Danish) translated it.
README.md - updated the translation percentage on the Danish translation.
app_da.arb - added missing translation file, and translated it.
More Language coverage, I guess.
Translated by a Danish citizen.
<br/>
<br/>
> feat(lang): add Danish language

- frontend/lib/l10n/app_de.arb
> Update German translation

- README.md
- frontend/lib/l10n/app_de.arb
<br/>
I updated the German translation to include all current strings and fixed some slightly off translations while doing so.
Missing translations added, wrong ones fixed.
<br/>
<br/>
> feat(lang): update German language file

- frontend/lib/l10n/app_pt.arb
Updated the latest strings and changed a few for better context.
<br/>
Updated the latest strings and changed a few for better context.
New strings for Portuguese plus a few changes for better understading.
<br/>
<br/>
> PT translation update

- frontend/lib/l10n/app_el.arb
<br/>
I'm happy to contribute the complete Greek localization for the Plant-it application. This addition will make the app more accessible to Greek-speaking users.
<br/>
<br/>
> feat: Add Greek (el) localization
