frontend/public/manifest.json

When you try to "install" the web app, it shows the default React values:
Before:
After:
I changed the name and the icons, but I don't know which colors will look good.

improve manifest

---

frontend/src/components/Auth.tsx
frontend/src/index.css

This PR fixes issue #9, i.e. add a check for the `username` and `password` field in the authentication page.
Before the PR it was possible to send empty login/signup requests and requests that does not match size requirement.
The response was not rendered correctly:
<p float="middle">
</p>
After the PR, a minimum/maximum length is forced in the `username` and `password` input. If the user tries to enter a text that does not match the size requirement in the signup page, the error source is highlighted and a helper text is displayed.
Also the "submit" button is disabled if:
- `username`/`password` contains some size error (signup)
- `username`/`password` is not provided (signin/signup)
<p float="middle">
<p>

Add input size check for username and password in authentication page

---

backend/src/main/java/com/github/mdeluise/plantit/plantinfo/PlantInfoExtractorFactory.java

This PR fixes issue #15, i.e. the trefle extractor is always added to the extractors chain, this leads to error since the system tries to send request to trefle system without a key.,

Fix trefle extractor always added to the extractors chain

---

backend/src/main/java/com/github/mdeluise/plantit/plant/PlantController.java
backend/src/main/java/com/github/mdeluise/plantit/plant/PlantRepository.java
backend/src/main/java/com/github/mdeluise/plantit/plant/PlantService.java
frontend/src/components/AddLogEntry.tsx
frontend/src/components/AddPlant.tsx
frontend/src/components/EditEvent.tsx
frontend/src/components/ErrorDialog.tsx
frontend/src/components/PlantDetails.tsx

This PR fixes issue #14, i.e. adds backend error message in the UI.
Example of rendered errors:
<p float="middle">
om/MDeLuise/plan" width="24%"  />
</p>

Add backend error messages in the UI

---

README.md
backend/pom.xml
backend/src/main/java/com/github/mdeluise/plantit/ApplicationConfig.java
backend/src/main/java/com/github/mdeluise/plantit/security/ApplicationSecurityConfig.java
backend/src/main/resources/application-dev.properties
backend/src/main/resources/application-integration.properties
backend/src/main/resources/application.properties
deployment/backend.env
deployment/frontend.env

This PR fixes issue #10, i.e. adds an environment variable `BASE_URL` used to set the CORS origin.
Other changes in this pull request:
- fix copyFiles property phase, now the run goal in `dev` profile also copy needed dummy file
- fix app description in Swagger UI

Add configurable CORS origin through environment variable

---

frontend/src/common.ts
frontend/src/components/Auth.tsx
frontend/src/components/Home.tsx

This PR fix a problem with the backend check in the `Auth` window, i.e. the check is performed on every `username` and `password` change and not only on window load.
Also:
- not send the `key` header when checking for backend availability
- add backend check even in the `Home` window
- better error message

Fix check backend connection only on windows load

---

frontend/src/components/Home.tsx
frontend/src/components/UserPlant.tsx

This PR introduces lazy load for plant images in the homepage window.
Before this, all plant images were loaded at the same time, resulting in a lot of background processing actions.
After this PR the images are loaded only when visible for the first time in the carousel.

Add lazy load for plant images in homepage

---

frontend/src/components/AddLogEntry.tsx
frontend/src/components/AllLogs.tsx
frontend/src/components/BottomBar.tsx
frontend/src/components/Home.tsx
frontend/src/components/PlantDetails.tsx

This PR adds the possibility of viewing the specific plant's log in the `Plant Details` window.
It also adds the feature of creating a new log entry clicking on the `Add event` button.
Before the PR:
<p align="center">
</p>
After the PR:
<p align="center">
</p>

Add event log view and "add log" possibility in the `Plant Details` window

---

frontend/src/components/EditEvent.tsx

This PR fixes an issue that sometime prevents the `note` field to update when viewing log events.

Fix event note not updating

---

frontend/src/components/PlantDetails.tsx

This PR fixes a bug which causes the first uploaded image of any plant to not be shown live in the `Plant Overview` window.

Fix not showing the first uploaded plant's image

---

frontend/src/common.ts
frontend/src/components/AddPlant.tsx
frontend/src/components/PlantDetails.tsx

This PR fixes a problem that occurs when trying to add a plant that uses a scientific classification that has an image that could not be loaded (e.g. because removed).
The scientific classification image result in infinite loading rendering, and a loop of error message are displayed.

Fix add plant with not loadable image

---

backend/src/main/java/com/github/mdeluise/plantit/diary/entry/DiaryEntryService.java

This PR fixes a problem that occurs when opening the `Plant overview` of an entity with 0 log entries.

Fix page size less then 1 error on plant details with no logs

---

deployment/docker-compose.yml

This PR adds a bind mount (similar to the one used for the upload dir) for the mysql database container to enable persistent storage.
Without a persistent storage solution, database information would get lost everytime the container is removed.

Add persistent database storage for mysql

---

frontend/src/components/AddPlant.tsx

This PR fix some bug in the add plant section of the app:
* set the correct fields values for the botanical info of the plant
* send the plant's `start date` only if selected
* send the default plant's state `ALIVE` instead of `PURCHASED`

Fix correct botanical info in the "add plant" section

---

frontend/src/components/AddPlant.tsx
frontend/src/components/Home.tsx
frontend/src/components/SearchPage.tsx

This PR fixes #49, i.e. when a new custom botanical info is created, that will be available immediately without requiring a page refresh.

Fix newer custom botanical info available only after component refresh

---

backend/pom.xml
backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfo.java
backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoDTO.java
backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoRepository.java
backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoService.java
backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/care/PlantCareInfoDTOConverter.java
backend/src/main/java/com/github/mdeluise/plantit/plantinfo/trafle/TrefleMigrator.java
backend/src/main/java/com/github/mdeluise/plantit/plantinfo/trafle/TrefleRequestMaker.java
backend/src/main/resources/application-dev.properties
backend/src/main/resources/application.properties
backend/src/main/resources/dblogs/changelog/changes/v0-0-0.xml
backend/src/main/resources/dblogs/changelog/init-dummy-data.xml
backend/src/test/java/com/github/mdeluise/plantit/botanicalinfo/service/BotanicalInfoServiceTest.java
frontend/src/components/AddPlant.tsx
frontend/src/components/EditableTextField.tsx
frontend/src/components/PlantDetails.tsx
frontend/src/components/SearchPage.tsx
frontend/src/interfaces.ts
online-resources/documentation/content/installation/configurations.md

I'm excited to share a new enhancement in this pull request. 🌱✨
I've introduced a "synonyms" field for user-created species. Now, you can easily search for a user-created species using any of its synonyms. This PR fixes #76.
This enhancement improves the search functionality, making it more intuitive for users. No need to remember the exact scientific name, simply search with any synonym, and Plant-it will find the matching species.
* Add a user-created species: when creating a new species, you can now include its synonyms.
* When "clone" a species from Trefle, the synonyms will be imported.
* Effortless Searching: Use any synonym to search for a species, and Plant-it will display the relevant user-created species.

Introducing synonyms field for user-created species

---

backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoController.java
backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoService.java
backend/src/main/java/com/github/mdeluise/plantit/plant/PlantController.java
backend/src/main/java/com/github/mdeluise/plantit/plant/PlantService.java
backend/src/main/java/com/github/mdeluise/plantit/stats/StatsController.java
backend/src/main/java/com/github/mdeluise/plantit/stats/UserStats.java
backend/src/main/java/com/github/mdeluise/plantit/systeminfo/StatsService.java
backend/src/test/java/com/github/mdeluise/plantit/plant/controller/PlantControllerTest.java
backend/src/test/java/com/github/mdeluise/plantit/plant/service/PlantServiceTest.java
frontend/src/components/Settings.tsx
frontend/src/interfaces.ts

In this update, I've consolidated user statistics into a dedicated endpoint. Previously spread across multiple endpoints, user stats are now conveniently accessible in one centralized location.
By streamlining the user stats into a single endpoint, I aim to simplify access and provide a more cohesive experience. This change enhances the efficiency of retrieving user-related data, making it easier for you to gather the insights you need.
To access user statistics, simply make a request to the new dedicated endpoint `GET /stats`. The response will contain comprehensive user stats, making it more straightforward to integrate this data into your Plant-it experience.

Move user stats to dedicated endpoint

---

backend/src/main/java/com/github/mdeluise/plantit/image/PlantImageRepository.java
backend/src/main/java/com/github/mdeluise/plantit/image/storage/FileSystemImageStorageService.java
backend/src/test/java/com/github/mdeluise/plantit/image/storage/service/FileSystemImageStorageServiceTest.java
frontend/public/sw.js
frontend/src/components/PlantDetails.tsx

Hi Plant-it Community!
This PR addresses an issue with image sorting. Now, the images are correctly sorted from the most recent to the oldest, ensuring a better user experience when browsing through images.
The correct sorting of images is crucial for users to easily access and navigate through the content. This fix ensures that the images are displayed in the intended order, improving the overall usability of the application.

Fix image sorting issue

---

backend/src/main/java/com/github/mdeluise/plantit/image/EntityImage.java
backend/src/main/java/com/github/mdeluise/plantit/image/EntityImageImpl.java
backend/src/main/java/com/github/mdeluise/plantit/image/ImageController.java
backend/src/main/java/com/github/mdeluise/plantit/image/ImageDTO.java
backend/src/main/java/com/github/mdeluise/plantit/image/PlantImageRepository.java
backend/src/main/java/com/github/mdeluise/plantit/image/storage/FileSystemImageStorageService.java
backend/src/main/java/com/github/mdeluise/plantit/image/storage/ImageStorageService.java
backend/src/main/java/com/github/mdeluise/plantit/plant/PlantAvatarGetter.java
backend/src/main/resources/dblogs/changelog/changes/v0-0-0.xml
backend/src/main/resources/dblogs/changelog/init-dummy-data.xml
backend/src/test/java/com/github/mdeluise/plantit/image/storage/service/FileSystemImageStorageServiceTest.java
frontend/src/components/PlantDetails.tsx

<br/>
I've made some updates to address the issue regarding the incorrect creation date for uploaded images.
Now, the creation date of uploaded images reflects the actual creation date rather than the upload date.
This change ensures that the creation date of images accurately represents when they were originally created, providing users with more precise data management.
Simply upload images as usual, and the system will automatically set the creation date based on the original creation date of the image file.
<br/>
<br/>

Fix creation date for uploaded images

---

frontend/src/components/PlantDetails.tsx

<br/>
This PR adds the ability to add multiple images for your plants all at once. This enhancement makes managing your plant images even more convenient and efficient.
Users can now select and upload multiple images for their plants simultaneously, streamlining the process of adding visual content to plant profiles.
This feature empowers users to enrich their plant profiles with multiple images, enhancing their plant-sharing experience.
1. Navigate to the plant profile you wish to add images to.
2. Click on the "Add Images" button.
3. Select multiple images from your device using the file picker.

Upload multiple plants' images

---

backend/src/main/java/com/github/mdeluise/plantit/exception/ControllerExceptionHandler.java
backend/src/main/java/com/github/mdeluise/plantit/exception/ErrorMessage.java
backend/src/main/java/com/github/mdeluise/plantit/exception/error/ErrorCode.java
backend/src/main/java/com/github/mdeluise/plantit/exception/error/ErrorMessage.java
backend/src/main/java/com/github/mdeluise/plantit/security/apikey/ApiKeyFilter.java
backend/src/main/java/com/github/mdeluise/plantit/security/jwt/JwtTokenFilter.java

<br/>
I've made some enhancements to the error message responses to simplify and improve user experience.
I've streamlined the error messages across the application to make them more concise and user-friendly. Instead of lengthy error messages, users will now receive clear and straightforward error responses from the backend.
Improving the clarity of error messages is essential for enhancing user experience and reducing confusion. With simplified error messages, users can quickly understand what went wrong and take appropriate actions to resolve the issue.
No specific actions are required from users. They will automatically benefit from the improved error message responses whenever they encounter errors while using the application.
Frontend side needs to be updated …

Simplify error responses

---

frontend/src/components/AddOrModifyReminder.tsx
frontend/src/components/AddPlant.tsx
frontend/src/components/PlantDetails.tsx

This PR fixes a problem that was affecting the rendering of the reminders fields in the application.
This update addresses an issue where the reminders fields were not rendering properly, causing inconvenience to users trying to manage their reminders. With this fix, the reminders fields now displays correctly, ensuring a smoother user experience.
The proper rendering of the reminders fields is crucial for users who rely on our application to manage their schedules and tasks efficiently. By resolving this issue, we are enhancing the usability and reliability of our platform.
No action is required from users to benefit from this fix. Simply navigate to the reminders section within the application, and you'll notice that the fields now renders as expected, allowing …

Fixed issue with render of reminders fields

---

backend/src/main/java/com/github/mdeluise/plantit/plantinfo/PlantInfoExtractorFacade.java

This PR addresses the issue (#156) where a whitespace input in the search box caused an error. The solution involves adding a check to trim whitespace characters from the input before processing the search query.

Fix query with only whitespace

---

frontend/android/app/src/main/AndroidManifest.xml

<br/>
I’ve addressed an issue where users were unable to connect to the server via the Android App, resulting in the error message: "Ops! Cannot connect to Server!" (https://github.com/MDeLuise/plant-it/issues/166).
The issue causing the connection failure in the Android App has been identified and fixed. Users should now be able to connect to the server without any issues.
Ensuring that the Android App can successfully connect to the server is crucial for a seamless user experience. This fix resolves the connectivity issue, allowing users to fully utilize the app’s features.
No additional steps are required from the users. Simply update to the latest version of the app, and the connection issues should be resolved.
<br/>
<br/>

Fix Android Apk App Server Connection Issue

---

frontend/lib/l10n/app_it.arb
frontend/lib/reminders/reminder_add.dart
frontend/lib/reminders/reminder_edit.dart

<br/>
This pull request addresses the translation issue for the reminder dropdown (https://github.com/MDeLuise/plant-it/issues/171).
Proper translation ensures a better user experience, allowing users to understand and interact with the application in their preferred language.
No additional steps are required. Once merged, the translations for the reminder dropdown will be applied automatically.
<br/>
<br/>

Fix translation issue for reminder dropdown

---

backend/src/main/java/com/github/mdeluise/plantit/plantinfo/trafle/TrefleRequestMaker.java
backend/src/main/resources/application-dev.properties
backend/src/main/resources/application-integration.properties
backend/src/main/resources/application.properties

Add an ability to specify custom Trefle Url. 
While you are working on another solution, I'm trying to deploy Trefle locally so that I can use Plant-it. Unfortunately, there is no way to change trefle domain available.
Similarly to `trefle.key`, just set the custom server URL.

feat: allow to customize Trefle url

---

README.md
backend/src/main/java/com/github/mdeluise/plantit/notification/dispatcher/NotificationDispatcherController.java
backend/src/main/java/com/github/mdeluise/plantit/notification/dispatcher/NotificationDispatcherName.java
backend/src/main/java/com/github/mdeluise/plantit/notification/gotify/GotifyNotificationDispatcher.java
backend/src/main/java/com/github/mdeluise/plantit/notification/gotify/GotifyNotificationDispatcherConfig.java
backend/src/main/java/com/github/mdeluise/plantit/notification/gotify/GotifyNotificationDispatcherConfigDTO.java
backend/src/main/java/com/github/mdeluise/plantit/notification/gotify/GotifyNotificationDispatcherDTOConverter.java
backend/src/main/java/com/github/mdeluise/plantit/notification/ntfy/NtfyNotificationDispatcher.java
backend/src/main/resources/application-dev.properties
backend/src/main/resources/application-integration.properties
backend/src/main/resources/application.properties
backend/src/main/resources/dblogs/changelog/changes/v1-0-0.xml
frontend/lib/l10n/app_en.arb
frontend/lib/l10n/app_it.arb
frontend/lib/main.dart
frontend/lib/more/change_notifications.dart
frontend/lib/more/gotify_settings.dart
frontend/lib/more/more_page.dart
frontend/lib/notify_conf_notifier.dart
online-resources/documentation/docs/server-installation.md

<br/>
This PR fixes #258, i.e. introduce a new feature that adds support for Gotify notifications. This addition will allow users who use Gotify for their notification needs to integrate seamlessly with the application.
I have implemented Gotify notification support in the application. Users can now configure the application to send notifications via Gotify by setting up the appropriate server properties.
Many users and organizations utilize Gotify for their notification systems. By adding support for Gotify, we provide more flexibility and options for our users to integrate their preferred notification services.
To enable Gotify notifications, you need to configure the new `GOTIFY_ENABLED=true` server property.
<br/>
<br/>

Add Gotify Notification Support

---

deployment/Dockerfile
deployment/start.sh

Hey Plant-it community!  
<br/>
I've made a significant change to the Docker configuration by switching the base image from Ubuntu to Alpine. This change is aimed at reducing the overall size of the Docker image and improving efficiency.
- **Base Image Change**: The Dockerfile now uses `alpine:3.20.2` instead of `ubuntu:24.04`.
- **Image Size Reduction**: This switch has considerably reduced the image size.
- **Smaller Image Size**: Using Alpine, which is a smaller base image compared to Ubuntu, helps in reducing the Docker image size. This not only saves disk space but can also improve download and deployment times.
- **Resource Efficiency**: A smaller image size can lead to more efficient use of resources, which is particularly beneficial for environments with limited resources, such as …

Switch Base Image from Ubuntu to Alpine to Reduce Image Size

---

README.md
backend/src/main/resources/application.properties
deployment/Dockerfile
deployment/helm/templates/config.yml
deployment/helm/values.yaml
deployment/kubernetes/config.yml
deployment/start.sh
online-resources/documentation/docs/server-installation.md

<br/>
In this update, I've removed the deprecated SSL feature from the project. This change is aimed at simplifying the setup and avoiding potential issues with outdated or unsupported SSL configurations.
I've eliminated the deprecated SSL configuration that was previously part of the setup. This change helps keep our codebase up-to-date with modern practices and reduces the potential for security vulnerabilities.
Removing deprecated features helps maintain a clean and lightweight codebase.
For users who still need SSL functionality, I recommend using established solutions such as [Nginx](https://nginx.org/en/) or [Traefik](https://doc.traefik.io/traefik/). These tools offer comprehensive SSL support and are widely used in production environments.
- If you have …

Remove Deprecated SSL Feature

---

backend/src/main/java/com/github/mdeluise/plantit/notification/email/EmailService.java
backend/src/test/java/com/github/mdeluise/plantit/unit/service/EmailServiceUnitTests.java

Hey Plant-it community!  
<br/>
Thir PR fixes #289. I've implemented a fix to ensure that the `FROM` address in our outgoing emails consistently matches the SMTP username. This change prevents issues with certain mail servers, that enforce strict checks on the `FROM` address and could reject our emails if there's a mismatch.
By explicitly setting the `FROM` address to match the SMTP username, we ensure better email deliverability and improve the security of our email-sending process.
No changes are required from the user side. The system will automatically use the correct `FROM` address when sending emails, ensuring consistency and reliability.
<br/>
<br/>

Fix email `FROM` address to ensure it matches SMTP username

---

frontend/lib/plant_details/plant_details_page.dart
frontend/lib/search/species_details_page.dart

Hey Plant-it community!  
<br/>
This PR fixes #282, i.e. adds a shadow to the back arrow on the plant details screen to improve its visibility, especially against a white background. This change helps the arrow stand out, making navigation easier for users.
The back arrow on the plant details screen was sometimes difficult to see against a white background, potentially leading to a poor user experience. Adding a shadow enhances the arrow's visibility, ensuring that users can easily find and use it.
No special instructions are needed. The back arrow on the plant details screen will now automatically have a shadow, making it more distinguishable against various backgrounds.
<br/>
<br/>

Add shadow to back arrow on plant details screen for improved visibility

---

frontend/lib/signup.dart

<br/>
This PR fixes #274, i.e. updates the regular expression used for validating email addresses to accommodate Top-Level Domains (TLDs) of any length. 
- **Regex Update**: The regex pattern has been modified to allow TLDs with 2 or more characters, removing the previous limit of 4 characters. This change ensures compatibility with a wider range of TLDs, including newer and longer ones.
- **Support for Modern TLDs**: The previous regex did not support TLDs longer than 4 characters, which could exclude valid email addresses with TLDs such as `.photography` or `.green`. This update ensures that email validation is more robust and aligns with current domain naming practices.
- **Local and Custom TLDs**: The update addresses issues faced by users with local email …

Update email regex to support TLDs of any length

---

frontend/lib/commons.dart
frontend/lib/event/add_new_event.dart
frontend/lib/event/edit_event.dart
frontend/lib/event/events.dart
frontend/lib/event/recent_events.dart
frontend/lib/plant_add/add_plant_page.dart
frontend/lib/plant_details/plant_tab.dart
frontend/lib/plant_edit/edit_plant_page.dart
frontend/lib/search/search_page.dart
frontend/lib/species_add/add_species_page.dart
frontend/lib/species_edit/edit_species_page.dart

<br/>
This PR fixes #196, i.e. addresses the text encoding issues reported by users, where Greek letters and special characters were being displayed incorrectly (often as gibberish or symbols) when saving and displaying plant names or other textual data.
Ensuring proper text encoding across the app is crucial for providing a consistent user experience, especially for users entering plant names or other data in non-Latin scripts, such as Greek. Additionally, fixing this encoding issue will improve the handling of special characters, including monetary symbols, which were previously causing errors when editing and saving plant details.
This fix is applied at the system level, ensuring that all text data processed and displayed by the app is properly encoded in UTF-8. …

Fix text encoding issues for special characters

---

frontend/lib/plant_add/add_plant_page.dart
frontend/lib/search/species_details_bottom_bar.dart
frontend/lib/search/species_details_page.dart

<br/>
This PR fixes #314, i.e. addresses an issue where attempting to add a plant from the same genus species that already exists in the user's collection would result in an error if the page is not reloaded before. The error was traced back to an assertion failure in Hibernate, which occurred during the collection initialization. 
User can now add multiple plants for a species belonging to floracodex without need to manually refresh the search page after the first plant added. 
No additional actions are required from users.
<br/>
<br/>

Resolve error when adding duplicate genus species before page reload
